# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: M2RjMDIzN2YyMzYxNGFmNGI3ZDk5ZGE5YTkzY2NiMTk0ZmY0NTAxOGI1N2NmM2UxM2I0ZWJmMjIwZjVmYzFlZjgzYjA5NDgzNWM4YjdiNWY3OGI5YzU5NGY4M2FiNWUzMGI0ODJjYTZkMDgyYTE5M2ZjMWZkOWNkNjQ5NzM1NmE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
